steps:
  # Step 1: Build Docker image locally
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'nginx-temp', '.']

  # Step 2: Login to Docker Hub using secret
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$DOCKER_PASSWORD" | docker login -u ram0810 --password-stdin
    secretEnv:
      - DOCKER_PASSWORD

  # Step 3: Tag image with Docker Hub name
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'nginx-temp', 'docker.io/ram0810/nginx-sample:latest']

  # Step 4: Push image to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'docker.io/ram0810/nginx-sample:latest']

availableSecrets:
  secretManager:
    - versionName: projects/my-gcp-project/secrets/docker-hub-credentials/versions/latest
      env:
        - DOCKER_PASSWORD
